package com.github.skonst07.aicodereviewer.api

import com.google.gson.Gson
import com.google.gson.JsonParser
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import okhttp3.MediaType.Companion.toMediaType



class GeminiApiClient {
    private val gson = Gson()
    private val client = OkHttpClient()

    fun review(apiKey: String, prompt: String, onError: (String)->Unit, onResult: (String)-> Unit) {
        val body = gson.toJson(mapOf(
            "contents" to listOf(mapOf(
                "parts" to listOf(mapOf("text" to prompt))
            ))
        ))


        val request = Request.Builder()
            .url("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$apiKey")
            .post(body.toRequestBody("application/json".toMediaType()))
            .build()

        //try-catch part generated by claude AI
        try {
            client.newCall(request).execute().use { response ->
                val responseBody = response.body?.string()

                if (responseBody.isNullOrEmpty()) {
                    onError("Empty response")
                    return
                }

                if (!response.isSuccessful) {
                    onError("API error ${response.code}: $responseBody")
                    return
                }
                val text = JsonParser.parseString(responseBody)
                    .asJsonObject
                    .getAsJsonArray("candidates")
                    .get(0).asJsonObject
                    .getAsJsonObject("content")
                    .getAsJsonArray("parts")
                    .get(0).asJsonObject
                    .get("text").asString

                onResult(text)
            }
        } catch (e: Exception) {
            onError("Network error: ${e.message}")
        }
    }

}