package com.github.skonst07.aicodereviewer.UI

import com.intellij.ui.components.JBScrollPane
import com.intellij.util.ui.JBUI
import java.awt.BorderLayout
import java.awt.Font
import javax.swing.JPanel
import javax.swing.JTextArea
import com.intellij.openapi.application.ApplicationManager

class AIreviewerPanel : JPanel(BorderLayout()) {

    //Text area generated by claude AI
    private val textArea = JTextArea().apply {
        isEditable = false
        lineWrap = true
        wrapStyleWord = true
        font = Font("Monospaced", Font.PLAIN, 13)
        border = JBUI.Borders.empty(8)
        text = "Select code in the editor, then right-click → Review with AI."
    }

    init {
        add(JBScrollPane(textArea), BorderLayout.CENTER)
    }

    fun setText(content: String) {
        ApplicationManager.getApplication().invokeLater {
            textArea.text = content
            textArea.caretPosition = 0
        }

    }

    fun printError(content: String){
        ApplicationManager.getApplication().invokeLater {
            textArea.text = "Error: $content"
        }

    }
}